### PR TITLE
Pull request to merge branches for DG_Maxwell

### PR DESCRIPTION
**Pull request by Balavarun5**

### CODE REVIEW

**Comment by amanabt** [comment]
author:amanabt
You should not set backend to opencl in every file.
Just do it in main once and that should be sufficient.

**Comment by amanabt** [comment]
The unit test `test_Li_Lp_xi` has some problem in executing.

**Comment by amanabt** [comment]
@Balavarun5 
- Do not set backend to opencl in every file.
- The unit test `test_Li_Lp_xi` has some problem in executing.
- `Li_Lp_xi(L_xi_j, L_xi_p)` was supposed to act on the arrays `L_xi_j`, `L_xi_p`.
   But it itself is being changed inside the function. What is the point of passing those two arrays as 
   arguments of the function.
- Document every function after you have written it.
- Unused variable 'Weight_function' in `populateGlobalVariables` function in `global_variables.py`
- Add kdev relate files and folders to `.gitignore`.

**Comment by Balavarun5** [comment]
test_dx_dxi function in test_waveEqn has a tolerance of 1e-5. Pytest fails for lower tolerances. 
https://arrayfire.com/explaining-fp64-performance-on-gpus/ - Link explaining arrayfire's precision issues with f64.

**Comment by amanabt** [comment]
@Balavarun5 
I read this article you suggested me

**Comment by amanabt** [comment]
I read the article [https://arrayfire.com/explaining-fp64-performance-on-gpus/](url)
suggested by you. The article talked about the performance issues of GPUs when
handling F64 data. The precision remains the same.

Next time please read the full article before posting.

**Comment by amanabt** [comment]
I read the article [https://arrayfire.com/explaining-fp64-performance-on-gpus/](url)
suggested by you. The article talked about the performance issues of GPUs when
handling F64 data. The precision remains the same.

Next time please read the full article before posting.

**Comment by amanabt** [comment]
@Balavarun5 
Please do not send me a pull request without checking and cleaning up your code
with Codeacy.

**Comment by amanabt** [comment]
@Balavarun5 
Please give tab spaces only at the starting of the lines. If you have to give white spaces
between some words, please use spaces and not tabs.

**Comment by amanabt** [comment]
@Balavarun5 
Tracked down the source of error
`E   SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 342-343: truncated \xXX escape`.

This is happening when you are writing `:math:L_p(\xi)L_i(\xi) ` which at `\xi` is being read as `\x`
which is not a valid unicode character.
Now, the question is how to write LaTeX symbols in docstrings?
To do this you need to give `\\` instead of a `\` before special symbols.
[https://stackoverflow.com/questions/14841182/in-restructuredtext-greek-alpha-needs-other-greek-letters-only-when-ta](url)

So, our LaTeX text will now become `:math:L_p(\\xi)L_i(\\xi) `.
Please make these changes at all the have used some LaTeX symbol.

**Comment by amanabt** [comment]
We also need to write a unit test for the calculation of the A matrix. After all these changes are made
I will merge this pull request.

**Pull request closed without merging**
